#!/bin/bash
valid2=0
var=0
var2=0

#Argument verification block

case $# in
    1)
        echo "Please include matrix" >&2
        cat > "$var"
        exit 3
        ;;
    2)
        if [[ -r $2 && -s $2 ]]
        then
            var="/nfs/stak/users/carlsosp/os1/prog1/$2"
        else
            echo "Enter valid matrix" >&2
            exit 1
        fi
        ;;
    3)
        if [[ -r $2 && -s $2 ]]
        then
            if [[ -r $3 && -s $3 ]]
            then
                valid2=1
                var="/nfs/stak/users/carlsosp/os1/prog1/$2"
                var2="/nfs/stak/users/carlsosp/os1/prog1/$3"
            else
                echo "Error reading second matrix" >&2
                exit 1
            fi
        else
            echo "Error reading first matrix" >&2
            exit 1
        fi
        ;;
esac

#execution block

case $1 in
    dims)
        if [ $valid2 -ne 0 ]
        then
            echo "only one matrix allowed" >&2
            exit 1
        fi
        printf "Rows: "
        echo | wc -l < "$var"
        printf "Columns: "
        read -a arr < "$var"
        echo "${#arr[@]}"
        exit 0
        ;;
    transpose)
        if [ $valid2 -ne 0 ]
        then
            echo "Only one matrix allowed" >&2
            exit 1
        fi
        rows=0
        i=0
        declare -a output=()
        while read -a arr2 ;
        do
            for ((j=0; j<${#arr2[@]}; j++))
            do
                output[$i]=${arr2[$j]}
                ((i+=1))
            done
            ((rows+=1))
        done < "$var"
        read -a top < "$var"
        cols=${#top[@]}
        rows=0
        for ((i=0; i<$cols; i++))
        do
            for ((j=i; j<${#output[@]}; j+=cols))
            do
                printf "%s"${output[j]}
                printf "	"
            done
            printf "\n"
        done
        exit 0
        ;;
    mean)
        if [ $valid2 -ne 0 ]
        then
            echo "Only one matrix allowed" >&2
            exit 1
        fi
        declare -a sum=()
        row=0
        while read -a meanln ;
        do
            for ((i=0; i<${#meanln[@]}; i++))
            do
                ((sum[i] += meanln[i]))
            done
            ((row+=1))
        done < "$var"
        for ((i=0; i<${#sum[@]}; i++))
        do
            sum[$i]=$((sum[i] / row))
            printf "%s"${sum[$i]}
            printf "	"
        done
        echo
        exit 0
        ;;
    add)
        if [ $valid2 -ne 1 ]
        then
            echo "two valid matrices required" >&2
            exit 1
        fi
        lines=$(wc -l < $var)
        read -a top < "$var"
        length=${#top[@]}
        lines2=$(wc -l < $var2)
        read -a top < "$var2"
        length2=${#top[@]}
        if [ $length -ne $length2 ] || [ $lines -ne $lines2 ]
        then
            echo "Matrices are different dimensions, they must be equal" >&2
            exit 1
        fi
        declare -a m1=()
        declare -a m2=()
        i=0
        while read -a arr2 ;
        do
            for ((j=0; j<$length; j++))
            do
                m1[$i]=${arr2[$j]}
                ((i+=1))
            done
        done < "$var"
        i=0
        while read -a arr ;
        do
            for ((j=0; j<$length; j++))
            do
                m2[$i]=${arr[$j]}
                ((i+=1))
            done
        done < "$var2"
        l=0
        for ((i=0; i<$lines; i++))
        do
            for ((j=0; j<$length; j++))
            do
                temp=$((m1[l] + m2[l]))
                printf "%s"$temp
                printf "	"
                ((l+=1))
            done
            printf "\n"
        done
        exit 0
        ;;
    multiply)
        if [ $valid2 -ne 1 ]
        then
            echo "two valid matrices required" >&2
            exit 1
        fi
        echo "mult option"
        ;;
    \?) 
        echo "enter: dims, transpose, mean, add, or multiply" >&2
        exit 3
        ;;
esac
exit 0